INSERT INTO FORUM (ID, DESCRIPCION, MODERADO, TITULO) VALUES (-1, 'Foro de juegos', false, 'Juegos');
INSERT INTO FORUM (ID, DESCRIPCION, MODERADO, TITULO) VALUES (-2, 'Foro de musica', true, 'Musica');
INSERT INTO FORUM (ID, DESCRIPCION, MODERADO, TITULO) VALUES (-3, 'Foro de programacion', false, 'Programacion');
INSERT INTO FORUM (ID, DESCRIPCION, MODERADO, TITULO) VALUES (-4, 'Foro de humor', true, 'Humor');
INSERT INTO FORUM (ID, DESCRIPCION, MODERADO, TITULO) VALUES (-5, 'Foro de viajes', false, 'Viajes');

INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (false, -1,'Genshin impact es un juego estilo anime :D',  CURRENT_TIMESTAMP, 'Genshin impact', -1, 'user_1');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -2,'Lol es un juego competitivo muy chevere :D',  CURRENT_TIMESTAMP, 'League of legends', -1, 'mod');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -3,'Provided to YouTube by Universal Music Group Mona Lisa · Lil Wayne · Kendrick Lamar :D',  CURRENT_TIMESTAMP, 'Mona Lisa', -2, 'user_3');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -4,'TWICE "MORE & MORE" M/V :D',  CURRENT_TIMESTAMP, 'MORE & MORE', -2, 'user_1');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -5,'.NET es un framework de Microsoft que hace un enfasis en la transparencia de redes, con independencia de plataforma de hardware y que permite un rapido desarrollo de aplicaciones :D',  CURRENT_TIMESTAMP, '.NET', -3, 'user_2');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -6,'se utiliza para crear y mantener aplicaciones web de una sola pagina :D',  CURRENT_TIMESTAMP, 'Angular', -3, 'mod');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -7,'chiste malo 1. lorem ipsum chiste :D',  CURRENT_TIMESTAMP, 'Chistes malos', -4, 'user_1');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -8,'chiste malo 2. lorem ipsum chiste :D',  CURRENT_TIMESTAMP, 'Chistes malos v2.0', -4, 'admin');
INSERT INTO TOPIC (APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, TITULO, FORO_ID, OWNER_USERNAME) VALUES (true, -9,'Pais con hermosa naturaleza :D',  CURRENT_TIMESTAMP, 'Colombia', -5, 'user_3');

INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -1, 'Me encanta este juego', CURRENT_TIMESTAMP, 'user_2', -1);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -10, 'Los mejores graficos', CURRENT_TIMESTAMP, 'user_3', -1);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -2, 'Un juego competitivo', CURRENT_TIMESTAMP, 'admin', -2);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -3, 'El mejor rap', CURRENT_TIMESTAMP, 'user_2', -3);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -4, 'Amo el kpop', CURRENT_TIMESTAMP, 'mod', -4);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -5, 'Soy programador .net', CURRENT_TIMESTAMP, 'user_1', -5);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -6, 'Soy programador Front end', CURRENT_TIMESTAMP, 'user_2', -6);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -7, 'Ese chistoe me hizo dar ganas de arrancarme un ojo', CURRENT_TIMESTAMP, 'user_3', -7);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -8, 'Malisimo', CURRENT_TIMESTAMP, 'user_2', -8);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID) VALUES (true, -9, 'Lo visite una vez y me encanto el cafe', CURRENT_TIMESTAMP, 'user_3', -9);

INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -11, 'A mi tambien', CURRENT_TIMESTAMP, 'user_3', -1, -1);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -12, 'Respondo comentarios', CURRENT_TIMESTAMP, 'user_2', -2, -2);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -13, 'Respondo comentarios', CURRENT_TIMESTAMP, 'mod', -3, -3);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -14, 'Respondo comentarios', CURRENT_TIMESTAMP, 'user_2', -4, -4);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -15, 'Respondo comentarios', CURRENT_TIMESTAMP, 'user_3', -5, -5);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -16, 'Respondo comentarios', CURRENT_TIMESTAMP, 'mod', -6, -6);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -17, 'Respondo comentarios', CURRENT_TIMESTAMP, 'user_1', -7, -7);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -18, 'Respondo comentarios', CURRENT_TIMESTAMP, 'admin', -8, -8);
INSERT INTO COMMENT(APROBADO, ID, CONTENIDO, FECHA_PUBLICACION, OWNER_USERNAME, TEMA_ID, PADRE_ID)  VALUES (true, -19, 'Respondo comentarios', CURRENT_TIMESTAMP, 'user_2', -9, -9);

INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-1, true, 'admin', -1);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-2, true, 'user_1', -2);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-3, false, 'user_2', -3);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-4, true, 'user_3', -4);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-5, false, 'mode', -5);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-6, true, 'admin', -6);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-7, false, 'mod', -7);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-8, true, 'user_1', -8);
INSERT INTO COMMENT_VOTE (ID, ME_GUSTA, OWNER_USERNAME, COMENTARIO_ID) VALUES (-9, false, 'user_2', -9);

INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-1, true, 'admin', -1);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-2, true, 'user_1', -2);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-3, false, 'user_2', -3);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-4, true, 'user_3', -4);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-5, false, 'mode', -5);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-6, true, 'admin', -6);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-7, false, 'mod', -7);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-8, true, 'user_1', -8);
INSERT INTO TOPIC_VOTE(ID, ME_GUSTA, OWNER_USERNAME, TEMA_ID) VALUES (-9, false, 'user_2', -9);